blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question
    url: https://github.com/twirphp/twirp/discussions/new?category=q-a
    about: Ask and discuss questions with other community members

  - name: ğŸ“š Documentation
    url: https://twirphp.readthedocs.io
    about: Check the documentation for help

  - name: ğŸ’¬ Slack channel
    url: https://gophers.slack.com/messages/C8T4Y2248
    about: Please ask and answer questions here
